// End-to-end local simulation of a full cross-chain OTC swap through the keeper.
// Requires two anvil chains: source on :8545, Arc on :8546.
// Deploys mock USDC + both escrows, then runs the whole dance and asserts balances.
import { ethers } from "ethers";
import { readFileSync } from "fs";
import { Keeper } from "./keeper.mjs";
import { ERC20_ABI, ESCROW_ABI } from "./abis.mjs";

const OUT = new URL("../contracts/out/", import.meta.url);
const art = (p) => JSON.parse(readFileSync(new URL(p, OUT)));
const MockUSDC = art("MockUSDC.sol/MockUSDC.json");
const ArcdeskEscrow = art("ArcdeskEscrow.sol/ArcdeskEscrow.json");

// anvil default keys (same accounts on both chains)
const KEYS = [
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80", // 0 deployer
  "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d", // 1 maker
  "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a", // 2 taker
  "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6", // 3 treasury
  "0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a", // 4 keeper
];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const eq = (a, b, msg) => {
  if (a.toString() !== b.toString()) throw new Error(`ASSERT ${msg}: ${a} != ${b}`);
  console.log(`  ok  ${msg}`);
};

async function deploy(signer, artifact, args) {
  const f = new ethers.ContractFactory(artifact.abi, artifact.bytecode.object, signer);
  const c = await f.deploy(...args);
  await c.waitForDeployment();
  return c;
}

async function main() {
  const SRC_URL = process.env.SRC_URL || "http://127.0.0.1:8545";
  const ARC_URL = process.env.ARC_URL || "http://127.0.0.1:8546";
  const src = new ethers.JsonRpcProvider(SRC_URL);
  const arc = new ethers.JsonRpcProvider(ARC_URL);
  src.pollingInterval = 400;
  arc.pollingInterval = 400;
  // Local anvil reports a stale "pending" nonce, so ethers reuses a consumed nonce on
  // the next tx. We await every tx before the next, so forcing each send to use the
  // "latest" mined nonce (with a monotonic local guard) is correct. Test-harness only.
  const manualNonce = (wallet) => {
    let next = -1;
    const origSend = wallet.sendTransaction.bind(wallet);
    wallet.sendTransaction = async (tx) => {
      const latest = await wallet.provider.getTransactionCount(wallet.address, "latest");
      const n = next > latest ? next : latest;
      next = n + 1;
      return origSend({ ...tx, nonce: n });
    };
    return wallet;
  };
  const S = KEYS.map((k) => manualNonce(new ethers.Wallet(k, src)));
  const A = KEYS.map((k) => manualNonce(new ethers.Wallet(k, arc)));
  const [dep, maker, taker, treasury, keeper] = [0, 1, 2, 3, 4];

  console.log("deploying source (Base sim, 6dp) ...");
  const baseUsdc = await deploy(S[dep], MockUSDC, [6]);
  const payEsc = await deploy(S[dep], ArcdeskEscrow, [await baseUsdc.getAddress(), A[keeper].address]);
  console.log("deploying arc (18dp) ...");
  const arcUsdc = await deploy(A[dep], MockUSDC, [18]);
  const liqEsc = await deploy(A[dep], ArcdeskEscrow, [await arcUsdc.getAddress(), A[keeper].address]);

  const baseAddr = await baseUsdc.getAddress();
  const arcAddr = await arcUsdc.getAddress();
  const payAddr = await payEsc.getAddress();
  const liqAddr = await liqEsc.getAddress();

  // fund
  await (await new ethers.Contract(arcAddr, ERC20_ABI, A[dep]).mint(A[maker].address, ethers.parseUnits("1000", 18))).wait();
  await (await new ethers.Contract(baseAddr, ERC20_ABI, S[dep]).mint(S[taker].address, ethers.parseUnits("1000", 6))).wait();

  // trade params: buy 100 Arc USDC, 50% premium -> 150 base proceeds, 2% fee -> 3 base
  const ARC_AMT = ethers.parseUnits("100", 18);
  const PROCEEDS = ethers.parseUnits("150", 6);
  const FEE = ethers.parseUnits("3", 6);
  const offerId = ethers.id("offer-1");
  const orderId = ethers.id("order-1");
  const secret = ethers.id("preimage-xyz"); // generated by the MAKER
  const hashlock = ethers.keccak256(ethers.solidityPacked(["bytes32"], [secret]));
  const now = (await arc.getBlock("latest")).timestamp;
  const offerExpiry = now + 3600;
  const resvDeadline = now + 7200; // maker commits long (> MIN_RESERVATION_WINDOW)
  const payDeadline = now + 1200; // taker pays short (< MAX_PAYMENT_WINDOW)

  // maker posts time-limited offer on Arc
  const arcUsdcMaker = new ethers.Contract(arcAddr, ERC20_ABI, A[maker]);
  await (await arcUsdcMaker.approve(liqAddr, ARC_AMT)).wait();
  const liqMaker = new ethers.Contract(liqAddr, ESCROW_ABI, A[maker]);
  await (await liqMaker.postOffer(offerId, ARC_AMT, 5000, offerExpiry)).wait();
  console.log("maker posted offer (100 USDC, 50% premium, 10min)");

  // start keeper
  const keeperSvc = new Keeper({
    paymentSigner: S[keeper],
    offerSigner: A[keeper],
    paymentAddr: payAddr,
    offerAddr: liqAddr,
  });
  // The desk plays maker here, so it holds the preimage and settles the payment itself.
  // The keeper only settles the exact quoted payment, so the order registry must carry the
  // payer and the terms it expects to see on-chain.
  keeperSvc.registerOrder(orderId, {
    offerId, recipient: A[taker].address, amount: ARC_AMT, hashlock, resvDeadline, secret,
    payer: S[taker].address, maker: S[maker].address,
    proceeds: PROCEEDS.toString(), fee: FEE.toString(),
  });
  await keeperSvc.start();

  // Maker commits first: the reservation exists before the taker sends any money.
  await keeperSvc.reserveForOrder(orderId);

  // taker locks payment on source chain
  const baseUsdcTaker = new ethers.Contract(baseAddr, ERC20_ABI, S[taker]);
  await (await baseUsdcTaker.approve(payAddr, PROCEEDS + FEE)).wait();
  const payTaker = new ethers.Contract(payAddr, ESCROW_ABI, S[taker]);
  await (await payTaker.lockPayment(orderId, S[maker].address, S[treasury].address, PROCEEDS, FEE, hashlock, payDeadline)).wait();
  console.log("taker locked payment (153 USDC)");

  // The taker sends exactly one transaction, on the source chain, and never touches Arc.
  const liqRead = new ethers.Contract(liqAddr, ESCROW_ABI, arc);
  const payRead = new ethers.Contract(payAddr, ESCROW_ABI, src);
  for (let i = 0; i < 120; i++) {
    const r = await liqRead.reservations(orderId);
    if (r.status === 2n) break; // Claimed = delivered
    await sleep(250);
  }
  for (let i = 0; i < 120; i++) {
    const p = await payRead.paymentOf(orderId, S[taker].address);
    if (p.status === 2n) break; // Claimed
    await sleep(250);
  }
  console.log("maker claimed payment, keeper delivered on Arc");

  // assertions
  console.log("assertions:");
  const arcBal = new ethers.Contract(arcAddr, ERC20_ABI, arc);
  const baseBal = new ethers.Contract(baseAddr, ERC20_ABI, src);
  eq(await arcBal.balanceOf(A[taker].address), ARC_AMT, "taker received 100 Arc USDC without transacting on Arc");
  eq(await arc.getTransactionCount(A[taker].address), 0, "taker sent zero Arc transactions");
  eq(await baseBal.balanceOf(S[maker].address), PROCEEDS, "maker received 150 base USDC");
  eq(await baseBal.balanceOf(S[treasury].address), FEE, "treasury received 3 base USDC fee");
  eq(await baseBal.balanceOf(payAddr), 0n, "payment escrow drained");

  await keeperSvc.stop();
  console.log("\nE2E PASS: full cross-chain swap settled through the keeper.");
  process.exit(0);
}

main().catch((e) => {
  console.error("E2E FAIL:", e);
  process.exit(1);
});
